package domain.constants;

public enum EDepartment {
    HUMAN_RESOURCE_TEAM,
    MANAGEMENT_DEPARTMENT,
    PRODUCT_DEVELOP_TEAM,
    PRODUCT_MANAGEMENT_TEAM,
    PRODUCT_REVIEW_TEAM,
    RISK_COVERING_TEAM,
    SUBSCRIPTION_MANAGEMENT_TEAM
}
